### ISSUE TITLE
[Feature Request] Add Documentation to Pages in Blueprints > Pages area

### ISSUE THREAD

**Issue by sarahkemp** [symphonists/documenter#16]
This is half feature request, half advice request.

I would like to be able to add documentation to a given page that I had created under `Blueprints > Pages` but they are not available in the multi-select. From the outside looking in, this doesn't look like an impossible task. I think I would need to call up all the pages that have been made to add to the multi-select, add the drawer and button to the individual Page page (this is sort of foggy), generate the correct URL for storage (shouldn't be hard?)... Am I getting this right? Am I going to run into a brick wall if I look at this too hard or should I go ahead and see if I can get this feature added? Would anyone else even use this feature?

Thanks for reading.

**Comment by nitriques** [comment]
> What kinds of things to do you document if not Pages and Data Sources?

The page and data sources pages are now available, so I am closing this issue.

> I don't have much to say about Sections/Entries, they are self explanatory and all you can do is add or edit.

Documenter serves as a place for client/end user documentation, not developer focused for the moment. But feel free to send a PR if you want!
