### ISSUE TITLE
saveConfig has been removed.

### ISSUE THREAD

**Issue by alexbirukov** [symphonists/documenter#21]
Administration::instance()->saveConfig has been removed, use Symphony::Configuration()->write()

public function uninstall() {
			Symphony::Database()->query("DROP TABLE `tbl_documentation`;");
			Symphony::Configuration()->remove('text-formatter', 'documentation');
			Symphony::Configuration()->remove('button-text', 'documentation');
			Symphony::Configuration()->write();
		}

		public function install() {
			Symphony::Database()->query(
				"CREATE TABLE `tbl_documentation` (
					`id` int(11) unsigned NOT NULL auto_increment,
					`title` varchar(255),
					`pages` text,
					`content` text,
					`content_formatted` text,
					PRIMARY KEY (`id`)
				) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;"
      );
			Symphony::Configuration()->set('text-formatter', 'none', 'documentation');
			Symphony::Configuration()->set('button-text', __('Documentation'), 'documentation');
			Symphony::Configuration()->write();
			return;
		}

**Comment by nitriques** [comment]
Would you mind sending a pull request please ? :)

**Comment by nitriques** [comment]
Fixed in 2.3.0
