### ISSUE TITLE
Error when trying to create new entry (Symphony 2.6.7 + Documenter 2.4.0)

### ISSUE THREAD

**Issue by twiro** [symphonists/documenter#23]
I get the following error when trying to create a new documenter entry with the abovementioned setup:

    Symphony Fatal Error: Call to undefined method contentExtensionDocumenterNew::Error()
    An error occurred in .../extensions/documenter/lib/class.form.php around line 106

I went back to documenter version 2.3.0 and that worked!

**Comment by nitriques** [comment]
The problem is [this change](https://github.com/symphonists/documenter/compare/2.3.0...2.4.0#diff-d0911e15b5a2e4a3278e8036278c8ac8R106) It's a merge commit that I messed up (See a73f18d5cd27ef729b40779a80f1ad05cf2d5b85) 

Should be `Widget::Error` . Wanna send a PR ? :)

**Comment by nitriques** [comment]
`2.4.1` is out with the fix. Thanks.
