### ISSUE TITLE
Help button layout apparently broken in Symphony 2.7beta2

### ISSUE THREAD

**Issue by animaux** [symphonists/documenter#25]
![bildschirmfoto 2017-01-25 um 14 15 15](https://cloud.githubusercontent.com/assets/446874/22291868/cc78ab68-e308-11e6-9ce8-d03b66d27594.png)

**Comment by animaux** [comment]
Problem is the class of the button collides with drawer formatting. Cannot figure out where that class is defined though.

**Comment by animaux** [comment]
OK, this is where the problem comes from: https://github.com/symphonycms/symphony-2/commit/5b9e33c771e03f187d3cb9960bae82ee794966fb#commitcomment-21412938

Fixing this in the extension CSS is possible but really dirty.

**Comment by nitriques** [comment]
> Fixing this in the extension CSS is possible but really dirty.

Why is it dirty ?

**Comment by animaux** [comment]
Dirty because the extension CSS has to override everything in Symphonys CSS that is supposed to target the drawer only. A bit like two steps forward, one step back.

**Comment by nitriques** [comment]
I know my fix was to make it reusable... damn. does adding context fixes the issue ?

**Comment by animaux** [comment]
Pretty sure it does.

**Comment by animaux** [comment]
Confirmed. It does fix the issue.

**Comment by nitriques** [comment]
Ok I'll take a look at this, thanks!

**Comment by nitriques** [comment]
Finally!!! https://github.com/symphonycms/symphony-2/commit/7f149964 Can you confirm that it's fixed ?

**Comment by animaux** [comment]
Fix confirmed! 👍

**Comment by nitriques** [comment]
Thanks!
