### ISSUE TITLE
Preferences UI initial Text Formatter setting is None

### ISSUE THREAD

**Issue by cylkee** [symphonists/documenter#27]
v2.4.3, Sym 2.6.11, PHP 5.6.31, MySQL 5.5.52

<s>It's not clear what is allowed in the Content field.  The README suggests HTML, however the `Auto-generate content ...` button inputs Markdown headings (also, `##` and not `###`).</s>

<s>HTML works but Markdown does not.  It would be great if Markdown was allowed in the Content field.</s>

Scratch that, I've edited the title of this issue. I found a setting in Preferences to specify Markdown.  However, the initial Text Formatter setting of `None` seems irrelevant in the drop-down, unless you know the specific wrapper/class to assign to H3 to make them collapse.  The README should mention about setting Markdown in Preferences and/or Markdown ought to be pre-selected because the `Auto-generate content ...` button inputs Markdown headings.

**Comment by nitriques** [comment]
@cylkee wanna send a PR please ? :+1:

**Comment by cylkee** [comment]
@nitriques Would love to, but I don't know how to do a PR yet.

**Comment by nitriques** [comment]
It's never to late to learn!

You can even do it 100% via the github interface.
I think it is only a matter of browsing to the file and click on the edit button.

**Comment by cylkee** [comment]
> You can even do it 100% via the github interface.
> I think it is only a matter of browsing to the file and click on the edit button.

Oh, that's cool.  Is it the pencil icon which says "Fork this project and edit the file"?

I had a look around the code.  At first I was going to attempt to change what was selected in the `install()` function of `extension.driver.php`, but then I remembered Markdown is an optional extension.

So `Auto-generate content...` makes the assumption that Markdown is installed.  Either this needs to be specified as a requirement in the README and it's pre-selected in the `install()` function, which I think I can do, or there needs to be some conditional checks and the `Auto-generate content...` needs to take account of the text formatters, which is beyond what I can code.

**Comment by nitriques** [comment]
> Oh, that's cool. Is it the pencil icon which says "Fork this project and edit the file"

yup! looks like you already found it ;)

> So Auto-generate content... makes the assumption that Markdown is installed.

Yup that's a problem!

> or there needs to be some conditional checks and the Auto-generate content... needs to take account of the text formatters, which is beyond what I can code.

Maybe we could only show the button if the Markdown formatter is enabled ? And hide the button when it is not ? And document this in the README ? WDYT ?

**Comment by cylkee** [comment]
> Maybe we could only show the button if the Markdown formatter is enabled ? And hide the button when it is not ? And document this in the README ? WDYT ?

Sounds good to me - that and the Markdown pre-selection in Preferences, if the text formatter exists.

I'm sorry, I don't feel confident in trying to code that.  I'm pretty nifty with HTML/CSS/JS, so I'll see where else I can contribute.

**Comment by nitriques** [comment]
> that and the Markdown pre-selection in Preferences, if the text formatter exists.

I would not do that. It's not "Symphony-like".

> I'm sorry, I don't feel confident in trying to code that. I'm pretty nifty with HTML/CSS/JS, so I'll see where else I can contribute.

No problem! Thanks for all you've done.

**Comment by nitriques** [comment]
@cylkee if you are curious about the fix, you can check 187f1bb99b
